### ISSUE TITLE
Allow dropdown menu in toolbar with sub array

### ISSUE THREAD

**Issue by A-312** [Ionaru/easy-markdown-editor#129]
**What is your feature request ? Please describe.**

Allow dropdown menu in toolbar.
![image](https://user-images.githubusercontent.com/18501150/68712804-c6689080-059c-11ea-9df2-413ff0ad1cc1.png)

**Describe the solution you'd like**

Allow sub array in `toolbar: []`.

**Todo :** JS + CSS

https://github.com/Ionaru/easy-markdown-editor/blob/a49da28f4d8dd7c776c517b5bc4949aaca0a4dbe/src/js/easymde.js#L2245-L2251 

```js
     if (item === '|') { 
         el = createSep(); 
     } else if (typeof item === 'array') { 
         el = createToolbarSubButton(item, self.options.toolbarTips, self.options.shortcuts);
     } else { 

```

<details>
  <summary>Fast css/demo</summary>
  
  Fast css.
  
  ```css
div.sub-menu > div > button.sub {
    display: block !important;
    margin:5px 0;
}

div.sub-menu > * {
    display: block !important;
}

.sub-menu {
    position:relative;
    display: inline-block;
    height: 14px;
    /* overflow: hidden; */
    padding: 0;
}

div.sub-menu > div {
    position:absolute;
    top:16px;
    border: 1px solid black;
    z-index:999;
    background:white;
}
```

html : 
```html
<div class="sub-menu">
    <!-- :before icon or background icon -->
    <div>
    <button class="sub ordered-list" type="button" title="Liste ordonnée (Ctrl-Alt-L)" tabindex="-1"><i class="fa fa-list-ol"></i></button>
    <button class="sub checklist" type="button" title="Liste de taches" tabindex="-1"><i class="fa fa-check-square-o"></i></button>
    </div>
</div>
```
 </details>
