### ISSUE TITLE
Set Fullscreen z-index

### ISSUE THREAD

**Issue by NicoHood** [Ionaru/easy-markdown-editor#302]
When opening the fullscreen mode, my fixed header navigation is on top of the editor. I've fixed that via css, it would be nice to have a config option for this, or at least some larger z-index value.

```scss
.EasyMDEContainer {
  .editor-toolbar {
    &.fullscreen {
      z-index: 100;
    }
  }
  .CodeMirror {
    &.CodeMirror-fullscreen {
      z-index: 100;
    }
  }
}
```
