### ISSUE TITLE
Dark Background?

### ISSUE THREAD

**Issue by httpjamesm** [Ionaru/easy-markdown-editor#327]
How do I set my background to another color using CSS/JS? The other dark mode thread did not help me.

**Comment by lexterror** [comment]
I would like it too!

**Comment by CaptainStealthy** [comment]
Anyone find a solution for this?

**Comment by Ionaru** [comment]
You can hide the toolbar in the options and call the preview method after initialisation.

**Comment by CaptainStealthy** [comment]
I was able to work around the issue with the following CSS... I'm posting this with the disclaimer that I am _not_ skilled with CSS/design (think the famous Peter Griffin GIF...) whatsoever, so feel free to modify this snippet if I've written it like an idiot.

It may look hacky to those more skilled than I, but it works for my purposes. 😝 

(replace my scss color variables with your own color vars/color codes as you see fit)

```scss
.EasyMDEContainer {
    background-color: $gray-800 !important;
}

.CodeMirror, .editor-preview {
    color: $white !important;
    border-color: $gray-600 !important;
    background-color: $gray-800 !important;
}

.cm-s-easymde .CodeMirror-cursor {
    border-color: $gray-600 !important;
}

.editor-toolbar button i {
    color: $white !important;
}

.editor-toolbar button.active, .editor-toolbar button:hover {
    background-color: $blue !important; // Fixes toolbar buttons from appearing as white when hovered or selected
}

.editor-preview pre {
    background-color: #333 !important; // This fixes code blocks in Markdown appearing with a white background
}
```
