### ISSUE TITLE
Get the editor to fill parent height

### ISSUE THREAD

**Issue by shajidhasan** [Ionaru/easy-markdown-editor#383]
Hello! I have a div of say... 1000px tall. How do I set the editor height to 100% to get it to fill full space? I know about min-height and max-height but the problem is, my div is dynamic. It changes its size in different screens.

Is it possible to get the editor to fill its parent? If so, how?

Thanks for all the work. Much appreciated.

**Comment by shajidhasan** [comment]
I managed to achieve this by writing these styles:
```css
.EasyMDEContainer {
    height: 100% !important;
    display: flex !important;
    flex-direction: column;
}
.CodeMirror {
    flex: 1;
}
```
Not sure if it's the correct way or a bad hack. Keeping this issue open still, in hope to hear from the author.

**Comment by Ionaru** [comment]
This seems to work.

```css
.EasyMDEContainer, .CodeMirror {
    height: 100% !important;
}
```
